# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SWDgJyKnXnz_rT6TBXL_u_lDFECBtkRS
"""

import matplotlib.pyplot as plt
import numpy as np

# 1. PARAMETERS FOR LUMPED THERMAL SYSTEM
# Governing ODE: tau * (dT/dt) + T = T_ambient + Delta_T_step
T_initial = 25.0  # Initial temperature (°C)
T_step = 100.0  # Applied step input temperature (°C)
delta_T = T_step - T_initial

time = np.linspace(0, 50, 500)  # Time horizon (seconds)
tau_values = [5.0, 10.0, 15.0]  # Time constants tau in seconds
colors = ['#1f77b4', '#ff7f0e', '#2ca02c']

plt.figure(figsize=(9, 5))

# 2. TRANSIENT RESPONSE COMPUTATION & PLOTTING
for tau, color in zip(tau_values, colors):
    T_response = T_initial + delta_T * (1.0 - np.exp(-time / tau))
    plt.plot(
        time,
        T_response,
        label=f'$\\tau = {tau:.0f}\\text{{ s}}$',
        color=color,
        linewidth=2,
    )
    # Mark 63.2% rise point (t = tau)
    t_tau = tau
    T_tau = T_initial + 0.632 * delta_T
    plt.scatter([t_tau], [T_tau], color=color, s=35, zorder=5)

# Reference lines
plt.axhline(
    T_step,
    color='darkred',
    linestyle='--',
    linewidth=1.2,
    label=f'Steady State ({T_step:.0f} °C)',
)
plt.axhline(
    T_initial + 0.632 * delta_T,
    color='gray',
    linestyle=':',
    alpha=0.7,
    label='63.2% Response Mark',
)

plt.title('Step Response of First-Order Lumped Thermal System', fontsize=12)
plt.xlabel('Time (s)', fontsize=10)
plt.ylabel('Temperature (°C)', fontsize=10)
plt.xlim(0, 50)
plt.ylim(20, 110)
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend(loc='lower right', fontsize=9)

plt.tight_layout()
plt.savefig('thermal_step_response.png', dpi=300)
plt.show()